# EMPLOYEE COMPENSATION INTELLIGENCE

# CHAPTER 1

# PROJECT OVERVIEW

**Domain:** Experience-Based Compensation Analytics

**Objective:** To analyze employee experience, departmental distribution, and salary structure in order to understand how experience levels influence compensation patterns across the organization.

**Business Problem:** The organization maintains employee records containing experience, department, and salary details, but lacks clear insight into whether compensation is consistently aligned with experience across different departments. The problem is to assess the relationship between employee experience and salary and identify departmental variations in pay structure.

**Dataset:** An employee Dataset of a specific organization containing 5000 customer records with 19 features.

# CHAPTER 2
# DATA LOADING AND INITIAL OVERVIEW

Before performing any analysis, it is essential to load the dataset and understand its basic structure. This step helps in gaining familiarity with the dataset, identifying the number of records available, understanding the type of data present in each column, and spotting any immediate data quality issues such as missing values or incorrect data formats. A thorough initial overview ensures that appropriate data pre-processing steps can be planned effectively.

# Step 1: Importing Required Library and Dataset

We begin by importing the Pandas library, which provides efficient data structures and functions for data manipulation and analysis. The dataset is then loaded into a Pandas DataFrame.The alias 'pd' is a common convention.

                    *Syntax:
                    import pandas as pd
                    
                    file_name = "Dummy_5000_Employee_Details_Dataset.csv"
                    
                    df = pd.read_csv(file_name)*

In [2]:
import pandas as pd
file_name = "Dummy_5000_Employee_Details_Dataset.csv"
df = pd.read_csv(file_name)

# Step 2: Understanding Dataset Dimensions

To understand the size of the dataset, we check the total number of rows and columns.
Rows represent individual records or observations, while columns represent features or attributes.
This gives an idea of how much data is available for analysis.

                    *Syntax:
                    df.shape*

In [3]:
print("Shape of dataset:", df.shape)

Shape of dataset: (5000, 19)

# Step 3: Checking Data Types of Columns

To understand the columns better, we examine the data type of each column in the dataset.
This step helps identify whether columns are stored as numeric, text, or date formats. 
It also helps detect columns that may require data type conversion before analysis.

                        *Syntax:
                        df.dtypes*

In [4]:
print("Data types:", df.dtypes)

Data types: Unnamed: 0              int64
Name                   object
Address                object
Salary                float64
DOJ                    object
DOB                    object
Age                     int64
Sex                    object
Dependents            float64
HRA                   float64
DA                    float64
PF                    float64
Gross Salary          float64
Insurance              object
Marital Status         object
In Company Years        int64
Year of Experience      int64
Department             object
Position               object
dtype: object

# Step 4: Previewing the Dataset

To get a quick visual understanding of how the data looks, we display the first few records.
This helps verify whether the data has been loaded correctly and provides insight into column names, value ranges, and data patterns.

                    *Syntax:
                    df.head()*

# Step 5: Dataset Information Summary

We generate a concise summary of the dataset.
This output provides details such as: Column names,Data types & Count of non-null values in each column.
It is especially useful for identifying missing values and understanding memory usage.

                    *Syntax:
                    df.info()*

In [5]:
print("Head:", df.head())

Head:    Unnamed: 0      Name                              Address     Salary  \
0           0  VgwbPyBn  jyNxKZtk St, piZQhYcARo, PUN 172813  149289.04
1           1  pgdYaIWk  PypVsqug St, iHyelKZbFc, BLR 580530   69761.64
2           2  eWgVBGVv  pfQezTVa St, YfIaELfpUw, BLR 155186  107633.14
3           3  LYDofRRu  wcTsbmFr St, UdylzZFFCU, AMD 843852  147408.65
4           4  vhLFHcRg  DdxKVhli St, cYOjpbMztB, BLR 713383   53447.06

          DOJ         DOB  Age     Sex  Dependents        HRA           DA  \
0  27-04-1998  27-03-1971   53   Other         2.0   8776.096  35233.66637
1  24-10-2020  12-12-1997   26    Male         0.0   9302.836  16464.42599
2  22-07-2020  20-08-1979   44  Female         2.0  13357.686  25402.46856
3  27-03-2007  07-06-1966   58    Male         1.0   6026.135  34789.87603
4  23-05-2017  19-11-1992   31    Male         2.0   7554.294  12614.02633

             PF  Gross Salary Insurance Marital Status  In Company Years  \
0  22142.724760  171156.07760       NaN        Widowed                26
1  10347.127920   85181.77407      Both         Single                 3
2  15964.273030  130429.02150       NaN       Divorced                 3
3  21863.823120  166360.83790       NaN        Married                17
4   7927.330359   65688.04997      Life        Married                 7

   Year of Experience       Department                    Position
0                  32            Sales              Sales Director
1                   5  Human Resources                HR Executive
2                  23        Marketing  Senior Marketing Executive
3                  37          Finance            Account Director
4                  10            Sales             Sales Executive

In [6]:
print("Info:")
print(df.info())

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          5000 non-null   int64
 1   Name                5000 non-null   object
 2   Address             5000 non-null   object
 3   Salary              5000 non-null   float64
 4   DOJ                 5000 non-null   object
 5   DOB                 5000 non-null   object
 6   Age                 5000 non-null   int64
 7   Sex                 5000 non-null   object
 8   Dependents          4877 non-null   float64
 9   HRA                 5000 non-null   float64
 10  DA                  5000 non-null   float64
 11  PF                  5000 non-null   float64
 12  Gross Salary        5000 non-null   float64
 13  Insurance           3762 non-null   object
 14  Marital Status      4877 non-null   object
 15  In Company Years    5000 non-null   int64
 16  Year of Experience  5000 non-null   int64
 17  Department          5000 non-null   object
 18  Position            5000 non-null   object
dtypes: float64(6), int64(4), object(9)
memory usage: 742.3+ KB
None

# Step 6: Statistical Summary of Data

We generate descriptive statistics for numerical columns.
This provides key statistical measures such as mean, minimum, maximum, standard deviation, and quartiles. It helps in understanding the distribution and spread of numerical data.

*Syntax:
df.describe()*

In [7]:
print("Describe:", df.describe(include='all'))

Describe:          Unnamed: 0      Name                              Address  \
count   5000.000000      5000                                 5000
unique          NaN      5000                                 5000
top             NaN  VgwbPyBn  jyNxKZtk St, piZQhYcARo, PUN 172813
freq            NaN         1                                    1
mean    2499.500000       NaN                                  NaN
std     1443.520003       NaN                                  NaN
min        0.000000       NaN                                  NaN
25%     1249.750000       NaN                                  NaN
50%     2499.500000       NaN                                  NaN
75%     3749.250000       NaN                                  NaN
max     4999.000000       NaN                                  NaN

               Salary         DOJ         DOB          Age     Sex  \
count     5000.000000        5000        5000  5000.000000    5000
unique            NaN        3721        4158          NaN       3
top               NaN  09-11-2020  21-12-1979          NaN  Female
freq              NaN           6           5          NaN    1674
mean     93861.627080         NaN         NaN    40.378600     NaN
std      33931.869545         NaN         NaN    11.293023     NaN
min      15042.700000         NaN         NaN    21.000000     NaN
25%      70556.305000         NaN         NaN    30.000000     NaN
50%      96270.790000         NaN         NaN    40.000000     NaN
75%     121182.540000         NaN         NaN    50.000000     NaN
max     149991.340000         NaN         NaN    60.000000     NaN

         Dependents           HRA            DA            PF   Gross Salary  \
count   4877.000000   5000.000000   5000.000000   5000.000000    5000.000000
unique          NaN           NaN           NaN           NaN            NaN
top             NaN           NaN           NaN           NaN            NaN
freq            NaN           NaN           NaN           NaN            NaN
mean       1.951405   7993.397892  22152.257486  13921.666148  110085.616311
std        1.303863   2335.079683   8008.251450   5032.814519   37476.080169
min        0.000000   3127.273000   3550.223601   2231.150832   22624.827880
25%        1.000000   6249.897000  16651.974658  10464.993560   85180.223460
50%        2.000000   7713.330000  22720.843385  14278.996005  110617.024450
75%        3.000000   9526.462500  28600.258830  17973.935858  141118.540100
max        4.000000  14787.699000  35399.416010  22246.890720  173050.731300

       Insurance Marital Status  In Company Years  Year of Experience  \
count       3762           4877       5000.000000         5000.000000
unique         3              4               NaN                 NaN
top         Both        Married               NaN                 NaN
freq        1292           2929               NaN                 NaN
mean         NaN            NaN          9.794600           19.378600
std          NaN            NaN          8.833347           11.293023
min          NaN            NaN         -1.000000            0.000000
25%          NaN            NaN          3.000000            9.000000
50%          NaN            NaN          7.000000           19.000000
75%          NaN            NaN         15.000000           29.000000
max          NaN            NaN         39.000000           39.000000

             Department Position
count              5000     5000
unique                5       40
top     Human Resources  QA Lead
freq               1035      198
mean                NaN      NaN
std                 NaN      NaN
min                 NaN      NaN
25%                 NaN      NaN
50%                 NaN      NaN
75%                 NaN      NaN
max                 NaN      NaN

# CHAPTER 3
# DATA PRE-PROCESSING

Raw data is rarely perfect for direct analysis. Data pre-processing involves cleaning and transforming the dataset to improve data quality, ensure consistency, and prepare it for accurate analysis and modeling. This step plays a crucial role in eliminating errors, handling missing information, and structuring the data in a meaningful way.

## 3.1 Handling Missing Values

Missing values can lead to inaccurate results if not handled properly.
Handling missing values ensures data completeness and prevents errors during analysis.
First, the check is for the total missing values in each column.

            *Syntax:df.isnull().sum()*

Depending on the requirement, missing values can be:

 a.Filled with appropriate values (mean, median, mode, or a fixed value)

             *Syntax: df.fillna(value, inplace=True)*
 
 b.Removed if they are very few or irrelevant
 
             *Syntax: df = df.dropna()*

 In this case we have categorical data as well as numberical data for which the customized syntax is used.

             *Syntax:*
                  *for col in df.select_dtypes(include=['float64','int64']).columns:
                    df[col] = df[col].fillna(df[col].mean())*

                 *for col in df.select_dtypes(include=['object']).columns:
                    df[col] = df[col].fillna(df[col].mode()[0])*

In [8]:
df.isnull().sum()

Unnamed: 0               0
Name                     0
Address                  0
Salary                   0
DOJ                      0
DOB                      0
Age                      0
Sex                      0
Dependents             123
HRA                      0
DA                       0
PF                       0
Gross Salary             0
Insurance             1238
Marital Status         123
In Company Years         0
Year of Experience       0
Department               0
Position                 0
dtype: int64

In [9]:
for col in df.select_dtypes(include=['float64','int64']).columns:
    df[col] = df[col].fillna(df[col].mean())

for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna(df[col].mode()[0])

#### 3.1.1 Verifying if the null values exist or not

                *Syntax:
                df.isnull().sum()*

In [10]:
df.isnull().sum()

Unnamed: 0            0
Name                  0
Address               0
Salary                0
DOJ                   0
DOB                   0
Age                   0
Sex                   0
Dependents            0
HRA                   0
DA                    0
PF                    0
Gross Salary          0
Insurance             0
Marital Status        0
In Company Years      0
Year of Experience    0
Department            0
Position              0
dtype: int64

## 3.2 Removing Duplicate Records

Duplicate records can distort analysis results by over-representing certain data points. This step ensures that every record in the dataset is unique and contributes fairly to the analysis. 
We check and remove duplicate rows.

                *Syntax: 
                    original_count = len(df)
                    df = df.drop_duplicates()
                    print(f"Removed {original_count - len(df)} duplicate rows.")

In [11]:
original_count = len(df)
df.drop_duplicates()
print(f"Removed {original_count - len(df)} duplicate rows.")

Removed 0 duplicate rows.

## 3.3 Correcting Data Types

Sometimes data is stored in an incorrect format, such as numeric values stored as text or date values stored as strings. 
Correct data types are essential for performing mathematical operations, comparisons, and time-based analysis.
We convert such columns to the appropriate data types.

            *Syntax: 
                    df["column_name"] = df["column_name"].astype("int")
                    df["date_column"] = pd.to_datetime(df["date_column"])

Since the datatype of DOJ & DOB was given as object, it is changed to datetime format, and the dependents coloumn is chaged to int which was identified as float in initial checks.

In [12]:
df['DOJ'] = pd.to_datetime(df['DOJ'], errors='coerce',dayfirst=True)
df['DOB'] = pd.to_datetime(df['DOB'], errors='coerce',dayfirst=True)
if 'Dependents' in df.columns:
    df['Dependents'] = pd.to_numeric(df['Dependents'], errors='coerce').fillna(0).astype(int)

##### Verifying the changes

In [13]:
print("Data types:", df.dtypes)

Data types: Unnamed: 0                     int64
Name                          object
Address                       object
Salary                       float64
DOJ                   datetime64[ns]
DOB                   datetime64[ns]
Age                            int64
Sex                           object
Dependents                     int64
HRA                          float64
DA                           float64
PF                           float64
Gross Salary                 float64
Insurance                     object
Marital Status                object
In Company Years               int64
Year of Experience             int64
Department                    object
Position                      object
dtype: object

## 3.4 Creating Derived Columns

Derived columns are new features created from existing data to provide additional analytical insights. Feature creation enhances the dataset by adding meaningful attributes that support deeper analysis.

In [14]:
# 1. Annual CTC (Total Cost to Company)
df["Annual_CTC"] = df["Gross Salary"] + df["PF"] + df["HRA"] + df["DA"]

# 2. Experience Band
df["Experience_Band"] = pd.cut(df["Year of Experience"],
                               bins=[0,5,10,20,30,40],
                               labels=["0-5","6-10","11-20","21-30","31+"])

# 3. Age Group
df["Age_Group"] = pd.cut(df["Age"],
                         bins=[18,25,35,45,55,65],
                         labels=["18-25","26-35","36-45","46-55","56+"])

# 4. Service Category
df["Service_Category"] = pd.cut(df["In Company Years"],
                                bins=[0,2,5,10,20,30],
                                labels=["0-2 yrs","3-5 yrs","6-10 yrs","11-20 yrs","21+ yrs"])

# 5. Salary Band
df["Salary_Band"] = pd.cut(df["Salary"],
                           bins=[0,50000,100000,150000,200000],
                           labels=["Low","Medium","High","Very High"])

# 6. Dependent Status
df["Dependent_Status"] = df["Dependents"].apply(lambda x: "Has Dependents" if x > 0 else "No Dependents")

# 7. Joining Year
df["Joining_Year"] = df["DOJ"].dt.year

# 8. Birth Year
df["Birth_Year"] = df["DOB"].dt.year

# 9. Career Stage
df["Career_Stage"] = df["Age"].apply(lambda x:
                                      "Early Career" if x < 30 else
                                      "Mid Career" if x < 45 else
                                      "Senior Career")

##### View updated dataset

In [15]:
df.head()

,Unnamed: 0,Name,Address,Salary,DOJ,DOB,Age,Sex,Dependents,HRA,...,Position,Annual_CTC,Experience_Band,Age_Group,Service_Category,Salary_Band,Dependent_Status,Joining_Year,Birth_Year,Career_Stage
0,0,VgwbPyBn,"jyNxKZtk St, piZQhYcARo, PUN 172813",149289.04,1998-04-27,1971-03-27,53,Other,2,8776.096,...,Sales Director,237308.564730,31+,46-55,21+ yrs,High,Has Dependents,1998,1971,Senior Career
1,1,pgdYaIWk,"PypVsqug St, iHyelKZbFc, BLR 580530",69761.64,2020-10-24,1997-12-12,26,Male,0,9302.836,...,HR Executive,121296.163980,0-5,26-35,3-5 yrs,Medium,No Dependents,2020,1997,Early Career
2,2,eWgVBGVv,"pfQezTVa St, YfIaELfpUw, BLR 155186",107633.14,2020-07-22,1979-08-20,44,Female,2,13357.686,...,Senior Marketing Executive,185153.449090,21-30,36-45,3-5 yrs,High,Has Dependents,2020,1979,Mid Career
3,3,LYDofRRu,"wcTsbmFr St, UdylzZFFCU, AMD 843852",147408.65,2007-03-27,1966-06-07,58,Male,1,6026.135,...,Account Director,229040.672050,31+,56+,11-20 yrs,High,Has Dependents,2007,1966,Senior Career
4,4,vhLFHcRg,"DdxKVhli St, cYOjpbMztB, BLR 713383",53447.06,2017-05-23,1992-11-19,31,Male,2,7554.294,...,Sales Executive,93783.700659,6-10,26-35,6-10 yrs,Medium,Has Dependents,2017,1992,Mid Career

## 3.5 Filtering Data

Filtering allows us to focus on specific subsets of the data based on conditions. This helps in performing targeted analysis for particular categories or groups.

            *Syntax:
                    filtered_df = df[df["Column_Name"] == "Value"]

In [16]:
## Employees by Department: Separates employees department-wise for focused departmental analysis.
    
df_sales = df[df["Department"] == "Sales"]
df_hr = df[df["Department"] == "Human Resources"]
df_finance = df[df["Department"] == "Finance"]
df_marketing = df[df["Department"] == "Marketing"]

## Employees by Career Stage: Segments workforce based on career progression levels.
    
df_early_career = df[df["Career_Stage"] == "Early Career"]
df_mid_career = df[df["Career_Stage"] == "Mid Career"]
df_senior_career = df[df["Career_Stage"] == "Senior Career"]

## Employees by Experience Band: Creates experience-based workforce segmentation.

df_exp_0_5 = df[df["Experience_Band"] == "0-5"]
df_exp_6_10 = df[df["Experience_Band"] == "6-10"]
df_exp_11_20 = df[df["Experience_Band"] == "11-20"]
df_exp_21_30 = df[df["Experience_Band"] == "21-30"]
df_exp_31_plus = df[df["Experience_Band"] == "31+"]


## Employees by Salary Band: Identifies compensation-based employee segments.
    
df_low_salary = df[df["Salary_Band"] == "Low"]
df_medium_salary = df[df["Salary_Band"] == "Medium"]
df_high_salary = df[df["Salary_Band"] == "High"]
df_very_high_salary = df[df["Salary_Band"] == "Very High"]

## Employees by Service Category: Segments employees based on tenure in the organization.

df_service_0_2 = df[df["Service_Category"] == "0-2 yrs"]
df_service_3_5 = df[df["Service_Category"] == "3-5 yrs"]
df_service_6_10 = df[df["Service_Category"] == "6-10 yrs"]
df_service_11_20 = df[df["Service_Category"] == "11-20 yrs"]
df_service_21_plus = df[df["Service_Category"] == "21+ yrs"]

## Employees by Dependent Status: Helps analyze benefit-related and demographic workforce trends.

df_with_dependents = df[df["Dependent_Status"] == "Has Dependents"]
df_without_dependents = df[df["Dependent_Status"] == "No Dependents"]

##### Verification of the filter

In [17]:
df_senior_career.head()

,Unnamed: 0,Name,Address,Salary,DOJ,DOB,Age,Sex,Dependents,HRA,...,Position,Annual_CTC,Experience_Band,Age_Group,Service_Category,Salary_Band,Dependent_Status,Joining_Year,Birth_Year,Career_Stage
0,0,VgwbPyBn,"jyNxKZtk St, piZQhYcARo, PUN 172813",149289.04,1998-04-27,1971-03-27,53,Other,2,8776.096,...,Sales Director,237308.56473,31+,46-55,21+ yrs,High,Has Dependents,1998,1971,Senior Career
3,3,LYDofRRu,"wcTsbmFr St, UdylzZFFCU, AMD 843852",147408.65,2007-03-27,1966-06-07,58,Male,1,6026.135,...,Account Director,229040.67205,31+,56+,11-20 yrs,High,Has Dependents,2007,1966,Senior Career
6,6,vjbszTQW,"LLOOZxHr St, iiZXVGMuRa, DEL 672793",146007.75,2022-07-12,1971-12-04,52,Other,2,6581.225,...,National Account Head,228088.70000,31+,46-55,0-2 yrs,High,Has Dependents,2022,1971,Senior Career
8,8,sIZQRTaq,"ZrqSMeKj St, BSMxlzAcjl, BLR 743922",134973.46,2005-11-06,1965-11-05,58,Other,1,9632.654,...,Technical Lead,217948.86829,31+,56+,11-20 yrs,High,Has Dependents,2005,1965,Senior Career
9,9,DTjnhgxd,"ZEeBgofu St, BGXeaFhWmT, CHN 978281",120881.83,2006-12-23,1968-09-24,55,Female,2,10167.817,...,National Marketing Manager,198276.04065,31+,46-55,11-20 yrs,High,Has Dependents,2006,1968,Senior Career

## 3.6 Aggregating Data

Aggregation is used to summarize data and extract higher-level insights.This helps in understanding trends, averages, and comparisons across different groups.

            *Syntax:
                    aggregated_df = df.groupby("Group_Column")["Target_Column"].agg("mean")

In [18]:
# Department-wise Headcount
df["Headcount"] = 1
dept_headcount = df.groupby("Department")["Headcount"].sum()

# Department-wise Average Annual CTC
dept_avg_ctc = df.groupby("Department")["Annual_CTC"].mean().round(2)

# Experience Band-wise Headcount
exp_band_headcount = df.groupby("Experience_Band",observed=True)["Headcount"].sum()

# Age Group-wise Headcount
age_group_distribution = df.groupby("Age_Group",observed=True)["Headcount"].sum()

# Service Category-wise Headcount
service_category_distribution = df.groupby("Service_Category",observed=True)["Headcount"].sum()

# Gender Distribution
gender_distribution = df.groupby("Sex")["Headcount"].sum()

# Marital Status Distribution
marital_status_distribution = df.groupby("Marital Status")["Headcount"].sum()

# Department-wise Average Salary
dept_avg_salary = df.groupby("Department")["Salary"].mean().round(2)

# Career Stage-wise Average Annual CTC
career_stage_ctc = df.groupby("Career_Stage")["Annual_CTC"].mean().round(2)

# Experience Band-wise Average Salary
exp_band_salary = df.groupby("Experience_Band",observed=True)["Salary"].mean().round(2)

# Dependent Status-wise Average Annual CTC
dependent_ctc = df.groupby("Dependent_Status")["Annual_CTC"].mean().round(2)

# Joining Year-wise Headcount Trend
joining_trend = df.groupby("Joining_Year")["Headcount"].sum()

# Birth Year-wise Workforce Distribution
birth_year_distribution = df.groupby("Birth_Year")["Headcount"].sum()

##### Verify the agregation

In [29]:
dept_headcount.reset_index()

        Department  Headcount
0          Finance        989
1  Human Resources       1035
2               IT       1005
3        Marketing        967
4            Sales       1004

In [30]:
df.to_csv("cleaned_dataset.csv", index=False)